trainingdbt:
  outputs:
    dev:
      dbname: postgres
      host: "{{ env_var('DB_HOST', 'localhost') }}"
      pass: admin
      port: "{{ env_var('DB_PORT', '5433') | int }}"
      schema: public
      threads: 1
      type: postgres
      user: postgres
  target: dev
